config/routes.rb
Skialpi::Application.routes.draw do
 
  root :to => 'static_pages#home'
  
  resources :bug_reports
  resources :users do
    member do
      get :achievements
      get :season
      get :top10
      get :stats
      get :turn_off_helpers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :locations
  resources :areas
  resources :tracks
  resources :achievements
  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/skusam', to: 'users#skusam'
  match '/skusam_sprac', to: 'users#skusam_sprac', via: 'put'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/registration', to: 'users#new'
  
  match '/locations/:id/area/new' => 'areas#new'
  match '/locations/:id/area/create' => 'areas#create', via: 'post'
  
  match '/areas/:id/track/new' => 'tracks#new'
  match '/areas/:id/track/create' => 'tracks#create', via: 'post'
  
  match '/tracks/:id/change_area' => 'tracks#change_area'
  match '/tracks/:id/change_area_proc' => 'tracks#change_area_proc', via: 'put'
  match '/tracks/:id/add_as_achievement' => 'tracks#add_as_achievement'
  match '/tracks/:id/add_as_achievement_proc' => 'tracks#add_as_achievement_proc', via: 'post'
  
   match 'update_areas' => 'achievements#update_areas'
   match 'update_tracks' => 'achievements#update_tracks'

   match 'stats' => 'stats#index'
   match 'stats/best' => 'stats#best'
   match 'stats/best_in_season' => 'stats#best_in_season'

   
 

end

app/models/user.rb
# encoding: utf-8

# == Schema Information
#
# Table name: users
# encoding: utf-8

#
#  id              :integer          not null, primary key
#  email           :string(255)
#  sex             :string(255)
#  show_email      :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#  password_digest :string(255)
#  about           :text
#  name            :string(255)
#  birthdate       :date
#  show_age        :boolean
#

class User < ActiveRecord::Base
  
  attr_accessible :email, :sex, :show_email, :password, :password_confirmation,
                  :about, :name, :birthdate, :show_age, :helpers
  
  has_secure_password
  
  has_many :bug_reports, dependent: :destroy
  has_many :achievements, dependent: :destroy
  has_many :tracks, through: :achievements
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  #validations
  validates :name, presence: true, length: { maximum: 60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :sex, presence: true,
                  format: { with: /[mf]/ }
  VALID_DATE_REGEX = /[0-9]{4}-[0-9]{2}-[0-9]{2}/
  validates :birthdate, presence: true,
                        format: { with: VALID_DATE_REGEX }
  
  def create_achievement(track, date, time, note)
    self.achievements.create!(track_id: track.id, date: date, time: time, note: note)
  end
  
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
  def achievements_ordered
    self.achievements.includes(:track => :area).order("date DESC")
  end
  
  def season_achievements
    self.achievements.where("date_part('year', date) = date_part('year', current_date)").includes(:track => :area).order("date DESC")
  end
  
  def top10_achievements
    self.achievements.select("*").where("date_part('year', date) = date_part('year', current_date)").includes(:track => :area).order("points DESC").limit(10)
  end
  
  def top10_points
    @a = self.top10_achievements
    top10_points_p @a
  end
  
  def top10_points_p(ttachv)
    @a = ttachv
    @sum = 0
    @a.each do |a|
      @sum += a.points
    end
    @sum
  end

  def place
    uid = ActiveRecord::Base.connection.quote(self.id)
    @query = "select place from (
              select u.id, rank() over (order by points desc) as place from (
                select user_id, sum(points) as points from achievements group by user_id
              ) t
              join users u on u.id = t.user_id
              ) u where u.id = #{uid}"

    @result = ActiveRecord::Base.connection.execute(@query)
    @place = @result.first["place"]

  end

  def place_before_me place
    place = place.to_i - 1
    return 0 if place == 0

    place = ActiveRecord::Base.connection.quote(place)
    @query = "select points from (
              select u.id, points, rank() over (order by points desc) as place from (
                select user_id, sum(points) as points from achievements group by user_id
              ) t
              join users u on u.id = t.user_id
              ) u where place = #{place}"

    @result = ActiveRecord::Base.connection.execute(@query)
    @pbm_points = @result.first["points"]
  end
  
  def sex_sk
    return "muž" if self.sex.eql?("m")
    return "žena" if self.sex.eql?("f")
  end

  def self.wt_sex sex
    return "muž" if sex.eql?("m")
    return "žena" if sex.eql?("f")
  end

  # google:
  def age
    now = Time.now.utc.to_date
    birthday = birthdate.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]  
  before_filter :admin_user, only: :destroy
  before_filter :not_signed_in_user, only: [:new, :create]
  
  def index
    @users = User.paginate(page: params[:page]).includes(:achievements)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    @user.show_email ||= false 
    @user.show_age ||= false
    
    if @user.save
      sign_in @user
      flash[:success] = "Boli ste úspešne zaregistrovaní."
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    stats
    render 'stats'
  end
  
  def edit
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Vaše údaje boli zmenené."
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
 
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Používateľ bol zmazaný."
    redirect_to users_url
  end 

  def turn_off_helpers
    @user = User.find(params[:id])
    @user.toggle!(:helpers)
    flash[:success] = "Všetky pomocné komentáre boli vypnuté."
    sign_in @user
    redirect_to @user
  end
  

  
  def achievements
    @user = User.find(params[:id])
    @achievements = @user.achievements_ordered.paginate(page: params[:page])
    
    @all_class = "active"
    @subtitle = "Všetky zjazdy"
    
    @sum = @achievements.sum(:points)
  end
  
  def season
    @user = User.find(params[:id])
    @achievements = @user.season_achievements.paginate(page: params[:page])
   
    @season_class = "active"
    year = Time.new.year
    @subtitle = "Sezóna - #{year}"
    
    @sum = @achievements.sum(:points)
    render 'achievements'
  end
  
  def top10
    @user = User.find(params[:id])
    @achievements = @user.top10_achievements
  
    @sum = @user.top10_points_p(@achievements)

    @achievements = @achievements.paginate(page: params[:page], :per_page => 10, :total_entries => @achievements.count)
    @top10_class = "active"
    @subtitle = "Top10"
    render 'achievements'
  end
  
  def stats
    @user = User.find(params[:id])
    @all_points = @user.achievements.sum(:points)
    @tracks_count = @user.achievements.count
    @season_points = @user.season_achievements.sum(:points)
    @seasons_tracks_count = @user.season_achievements.count
    @top10_points = @user.top10_points
    @last_achv = @user.achievements.last
   
    @stats_class = "active"
    @subtitle = "Štatistiky"

    unless @tracks_count == 0
      @place = @user.place
      @pbm_points = @user.place_before_me @place
    end

  end

    
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  # methods for controlling whether user is signed in
  private

    def signed_in_user
      redirect_to signin_url, notice: "Na tuto akciu potrebujete byt prihlaseni." unless signed_in? 
    end
    
    def not_signed_in_user
      redirect_to root_path if signed_in? 
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end


end

app/views/users/_user_footer.html.erb
  </div>
</div>

app/views/users/_user_header.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      
      <br />
      <b>Body spolu:</b> <%= @user.achievements.sum(:points) %> <br />
      <b>Body sezóna:</b> <%= @user.achievements.where("date_part('year', date) = date_part('year', current_date)").sum(:points) %>
      
      <div class="user-info">
      <b>Pohlavie:</b> <%= "muž" if @user.sex.eql?("m") %><%= "žena" if @user.sex.eql?("f") %><br />
      
      <% if @user.show_age %>
        <b>Vek:</b> <%= @user.age %> <br />
      <% end %>
      
      <b>Registrovaný:</b> <%= @user.created_at.to_date %> <br />
      
      <% if @user.show_email %>
        <b>Email:</b> <%= @user.email %><br />
      <% end %>

      <% unless @user.about.nil? || @user.about.empty? %>
        <b>O mne:</b> <%= @user.about %><br />
      <% end %>
      
      <% if current_user?(@user) %>
        <br /><br />
        <%= link_to "Pridať zjazd do denníčka", "/achievements/new", class: "btn btn-large btn-primary" %>
        
        <% if @user.helpers %>
          <br /><br />
          <%= link_to "Vypnúť pomocné hlásenia", turn_off_helpers_user_path %>
        <% else %>
          <br /><br />
          <%= link_to "Zapnúť pomocné hlásenia", turn_off_helpers_user_path %>
        <% end %>
      <% end %>
      
      <% if !current_user.nil? && current_user.admin? && !current_user?(@user) %>
        <%= link_to "[zmazať]", @user, method: :delete,
                                  data: { confirm: "Ste si istí?" } %>
      <% end %>
      </div>
    </section>
  </aside>
  
  <div class="span8">
    <ul class="nav nav-tabs">
      <li class="<%= @stats_class %>"><%= link_to "Štatistiky", stats_user_path(params[:id]) %></li>
      <li class="<%= @all_class %>"><%= link_to "Všetko", achievements_user_path(params[:id]) %></li>
      <li class="<%= @season_class %>"><%= link_to "Sezóna", season_user_path(params[:id]) %></li> 
      <li class="<%= @top10_class %>"><%= link_to "Top10", top10_user_path(params[:id]) %></li>
    </ul>
    
    <h3 class="center"><%= @subtitle %></h3>
    
    

app/views/users/achievements.html.erb
<%= render 'user_header' %>

<% if @achievements.empty? %>
  <div class="alert alert-warning center" style="margin-top: 50px">V tejto sekcii nie je evidovaný žiadny zjazd</div>
<% else %>

<strong> Body spolu: </strong> <%= @sum %>
<%= will_paginate(@achievements) %>

<table class="table table-striped">
  
  <th> Zjazd </th> <th> Náročnosť </th> <th>Body</th> <th> Dátum </th> <th> Čas </th> <th> Komentár </th>
  <% if !current_user.nil? && current_user.admin? %>
    <th></th>
  <% end %>
  
  <% @achievements.each do |achievement| %>
    <tr>
      <td> <%= link_to achievement.track.area.name + ":" + achievement.track.name, achievement.track %> </td>
      <td> <%= achievement.track.difficulty %> | <%= achievement.track.exposure %></td>
      <td> <%= achievement.points %> </td>
      <td> <%= achievement.date %> </td>
      <td> <%= achievement.time %> </td>
      <td> <%= achievement.note %> </td>
    </tr>
  <% end %>

</table>

<%= will_paginate(@achievements) %>
<% end %>

<%= render 'user_footer' %>

app/views/users/edit.html.erb
<% provide(:title, 'Registrácia') %>

<h1>Nastavenia účtu</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Meno *" %>
      <%= f.text_field :name %>
      
      
        <label class="radio inline">
          <%= f.radio_button :sex, "m" %>
          som muž *
        </label>
        <label class="radio inline">
          <%= f.radio_button :sex, "f" %>
          som žena *
        </label>
        
      <br /><br />

      <%= f.label :email, "E-mail *" %>
      <%= f.text_field :email %>
      
      <label class="checkbox"
        <%= f.check_box :show_email, checked: true %>
        zobrazovať e-mail ostatným používateľom
      </label>
      
      <br />
      
      <%= f.label "birthdate", "Dátum narodenia *" %>                
      <div id="datetimepicker" class="input-append">
        <input class="span3" id="date-input" name="user[birthdate]" data-format="yyyy-MM-dd" type="text" width="10"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
        <span class="add-on">
          <em>napr. 1980-04-23</em>
        </span>
      </div>
      
      <label class="checkbox"
        <%= f.check_box :show_age, checked: true %>
        zobrazovať môj vek ostatným používateľom
      </label>

      <script type="text/javascript">      
      $(function() {
        $('#datetimepicker').datetimepicker({
          pickTime: false,
        });
        var picker = $('#datetimepicker').data('datetimepicker');
        picker.setLocalDate(new Date('<%= @user.birthdate %>')); 
      });
      </script>

      <br /><br />      
      
      <%= f.label :password, "Heslo *" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Potvrdenie hesla *" %>
      <%= f.password_field :password_confirmation %>
      
      <br /><br />

      <%= f.label :about, "O mne" %>
      <%= f.text_area :about, placeholder: "Niečo o mne...", size: "x6" %>
      
        
      Údaje označené hviezdičkou (*) sú povinné  <br /> <br />
        
      <%= f.submit "Uprav", class: "btn btn-large btn-warning" %>
       
    <% end %> 

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Používatelia") %>

<h1> Používatelia </h1>

<p class = center>V systéme už máme <strong><%= @users.count %></strong> zaregistrovaných používateľov. </p>

<%= will_paginate %>

<table class="table table-striped">
  
  <th> Meno </th> <th> Pohlavie </th> <th> Počet bodov </th> <th> Body sezóna </th>
  <% if !current_user.nil? && current_user.admin? %>
    <th></th>
  <% end %>
  
  <% @users.each do |user| %>
    <tr>
      <td> <%= link_to user.name, user %> </td>
      <td> <%= user.sex_sk %> </td>
      <td> <%= user.achievements.sum(:points) %> </td>
      <td> <%= user.season_achievements.sum(:points) %> </td>
      <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
      <td>
        <%= link_to "[zmazať]", user, method: :delete,
                                  data: { confirm: "Ste si istí?" } %>
      </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>

</table>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Registrácia') %>

<h1>Registrácia</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <div class="alert alert-info justify">
        Sme radi, že stre prajavili záujem o registráciu v systéme Skialpi. Systém Vám umožní evidovať, aké zjazdy ste zlyžovali a na základe ich náročnosti Vám ich automaticky ohodnotí. 
        <br /><br />
        <strong>Sledujte</strong> ako sa posúvate v rebríčku <strong>najlepších</strong> lyžiarov stále <strong>vyššie</strong> a prebojujte sa až na prvú priečku! Ak aj po úspechu netúžite, systém Vám dáva skvelú možnosť evidovať si Vaše zjazdy a Vy budete mať neoceniteľný prehľad o tom, čo ste kedy zlyžovali.
      </div>

      <%= f.label :name, "Meno *" %>
      <%= f.text_field :name %>
      
      <%= f.label :sex, "Pohlavie *", class: "linline" %>
        <label for="user_sex_m" class="radio inline">
          <%= f.radio_button :sex, "m" %>
          som muž
        </label>
        <label for="user_sex_f" class="radio inline">
          <%= f.radio_button :sex, "f" %>
          som žena
        </label>
        
      <br /><br />

      <%= f.label :email, "E-mail *" %>
      <%= f.text_field :email %>
      
      <label class="checkbox">
        <%= f.check_box :show_email, checked: true %>
        zobrazovať e-mail ostatným používateľom
      </label>
      
      <br />
      
      <%= f.label :birthdate, "Dátum narodenia *" %>                
      <div id="datetimepicker" class="input-append">
        <input class="span3" id="date-input" name="user[birthdate]" data-format="yyyy-MM-dd" type="text" width="10"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
        <span class="add-on">
          <em>napr. 1980-04-23</em>
        </span>
      </div>
      
      <label class="checkbox">
        <%= f.check_box :show_age, checked: true %>
        zobrazovať môj vek ostatným používateľom
      </label>

      <script type="text/javascript">      
      $(function() {
        $('#datetimepicker').datetimepicker({
          pickTime: false,
        });
        var picker = $('#datetimepicker').data('datetimepicker');
        picker.setLocalDate(new Date('1990-01-01')); 
      });
      </script>

      <br /><br />      
      
      <%= f.label :password, "Heslo *" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Potvrdenie hesla *" %>
      <%= f.password_field :password_confirmation %>
      
      <br /><br />

      <%= f.label :about, "O mne" %>
      <%= f.text_area :about, placeholder: "Niečo o mne...", size: "x6" %>
      
        
      Údaje označené hviezdičkou (*) sú povinné  <br /> <br />
      
        
      <%= f.submit "Registruj", class: "btn btn-large btn-primary" %>
      
    <% end %>
 
  </div>
</div>

app/views/users/season.html.erb
<%= render 'user_header' %>

<%= will_paginate(@achievements) %>

<%= @achievements.count %>
<table class="table table-striped">
  
  <th> Zjazd </th> <th> Náročnosť </th> <th> Dátum </th> <th> Čas </th> <th> Komentár </th>
  <% if !current_user.nil? && current_user.admin? %>
    <th></th>
  <% end %>
  
  <% @achievements.each do |achievement| %>
    <tr>
      <td> <%= link_to achievement.track.name, achievement.track %> </td>
      <td> <%= achievement.track.difficulty %> | <%= achievement.track.exposure %></td>
      <td> <%= achievement.date %> </td>
      <td> <%= achievement.time %> </td>
      <td> <%= achievement.note %> </td>
    </tr>
  <% end %>

</table>

<%= will_paginate(@achievements) %>

<%= render 'user_footer' %>

app/views/users/stats.html.erb
<%= render 'user_header' %>

<% if signed_in? and current_user?(@user) %>
	<% if @tracks_count == 0 %>
		<div class="alert alert-success center">
			Ešte ste nezlyžovali žiadny zjazd. Zlyžujte svoj prvý zjazd a vstúpte ku hodnoteným používateľom.
		</div>
	<% else %>
		<div class="alert alert-success center">
			Gratulujeme, v rebríčku ste na <strong><%= @place %>. mieste</strong>.
			<% if @place.to_i != 1 %>
				Ak sa chcete posunúť na <%= @place.to_i - 1 %>. miesto, potrebujete získať ešte <strong><%= @pbm_points.to_i - @all_points%></strong> bodov.
			<% end %>
		</div>
	<% end %>

	<% if current_user.helpers %>
	<div class="alert alert-info center">
      Vitajte vo svojom <strong>denníčku</strong>. Môžete si v ňom prezerať všetky Vaše zjazdy, pomocou tlačidla vľavo pridávať nové zjazdy a sledovať, ako sa Vám pripočitávajú body za Vaše úspechy. Ak si neprajete zobrazovať tieto pomocné okná, jednoducho ich vypnite pomocou odkazu vľavo - Vypnúť pomocné hlásenia. Nebojte sa, ak si to rozmyslíte, tieto hlásenia môžete podobným spôsobom kedykoľvek opäť zapnúť.<br /><br />
      Pre bližšiu pomoc kedykoľvek kliknite na <u><%= link_to "Pomocníka", "/help" %></u> v spodnej časti stránky.
    </div>
    <% end %>
<% end %>

<br />

<div class="row">
  <div class="span8">
<table class="table" style="font-size: 16px">
<tr>
	<td>body spolu:</td><td><strong><%= @all_points %></strong></td>
</tr>
<tr>
	<td>body v sezóne <%= Date.current.year %>:</td><td><%= @season_points %></td>
</tr>
<tr>
	<td>body v TOP10:</td><td><%= @top10_points %></td>
</tr>
</table>
</div>
</div>

<br /><br />
Počet evidovaných zjazdov: <%= @tracks_count %><br />
Počet zjazdov evidovaných v sezóne <%= Date.current.year %>: <%= @seasons_tracks_count %><br /><br />

<% unless @last_achv.nil? %>
  Naposledy pridaný zjazd: <%= link_to @last_achv.track.name, @last_achv.track %> (<%=     @last_achv.created_at.to_date %>) <%= @last_achv.points %>b <br />
<% end %>

<%= render 'user_footer' %>