config/routes.rb
Skialpi::Application.routes.draw do
 
  root :to => 'static_pages#home'
  
  resources :bug_reports
  resources :users do
    member do
      get :achievements
      get :season
      get :top10
      get :stats
      get :turn_off_helpers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :locations
  resources :areas
  resources :tracks
  resources :achievements
  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/skusam', to: 'users#skusam'
  match '/skusam_sprac', to: 'users#skusam_sprac', via: 'put'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/registration', to: 'users#new'
  
  match '/locations/:id/area/new' => 'areas#new'
  match '/locations/:id/area/create' => 'areas#create', via: 'post'
  
  match '/areas/:id/track/new' => 'tracks#new'
  match '/areas/:id/track/create' => 'tracks#create', via: 'post'
  
  match '/tracks/:id/change_area' => 'tracks#change_area'
  match '/tracks/:id/change_area_proc' => 'tracks#change_area_proc', via: 'put'
  match '/tracks/:id/add_as_achievement' => 'tracks#add_as_achievement'
  match '/tracks/:id/add_as_achievement_proc' => 'tracks#add_as_achievement_proc', via: 'post'
  
   match 'update_areas' => 'achievements#update_areas'
   match 'update_tracks' => 'achievements#update_tracks'

   match 'stats' => 'stats#index'
   match 'stats/best' => 'stats#best'
   match 'stats/best_in_season' => 'stats#best_in_season'

   
 

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  attr_accessible :date, :note, :time, :track_id
  
  include TracksHelper
    
  belongs_to :user
  belongs_to :track
  
  validates :user_id, presence: true
  validates :track_id, presence: true
  
  before_save :count_points
  
  # default_scope order: "date DESC"
  
  def count_points
    self.points = difficulty_level_points(track.difficulty) + exposure_level_points(track.exposure)
  end
  
end

app/controllers/achievements_controller.rb
# encoding: utf-8

class AchievementsController < ApplicationController

  before_filter :signed_in_user

  def new
    @achievement = Achievement.new
    @locations = Location.all
  end
  
  def update_areas
        location = Location.find(params[:location_id])
        @areas = location.areas.map{|a| [a.name, a.id]}.insert(0, "Vyberte si oblasť")
  end
 
  def update_tracks
      area = Area.find(params[:area_id])
      @tracks = area.tracks.map{|t| [t.name, t.id]}.insert(0, "Vyberte si zjazd")
  end
  
  def create
    @achievement = Achievement.new(params[:achievement])
    @user = current_user
    
    unless params[:track_id].empty? or (params[:track_id].to_i == 0)
      @track = Track.find(params[:track_id]) 
      @user.create_achievement(@track, @achievement.date, @achievement.time, @achievement.note)
      flash[:success] = "Zjazd bol pridaný do denníčka."
      redirect_to @user
    else
      @achievement.errors.add("Track","can not be empty.")
      @locations = Location.all
      render 'new'
    end
    
  end
  
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/views/achievements/new.html.erb
<% provide(:title, 'Pridaj zjazd do denníčka') %>

<h1>Pridanie zjazdu do denníčka</h1>

<div class="row">
  <div class="span6 offset3">
 
  <%= form_for(@achievement) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
  

<%= collection_select(nil, :location_id, @locations, :id, :name, {:prompt => "Vyberte si lokalitu"}, {:id => 'locations_select'}) %>
<br/>

<% if @areas.nil? %>
  <select id="areas_select" name="[area_id]"><option value="">---</option></select>
  <br/>
<% else %>
  <%= collection_select(nil, :area_id, @areas, :id, :name, {:prompt => "Select an 2Area"}, {:id => 'areas_select'}) %>
  <br/>
<% end %>

<% if @areas.nil? %>
  <select id="tracks_select" name="[track_id]"><option value="">---</option></select>
  <br/>
<% else %>
  <%= collection_select(nil, :track_id, @tracks, :id, :name, {:prompt => "Select a 2Track"}, {:id => 'tracks_select'}) %>
  <br/>
<% end %>

<br /> <br />

      <%= f.label :date, "Dátum zjazdu *" %>                
      <div id="datetimepicker" class="input-append">
        <input class="span3" id="date-input" name="achievement[date]" data-format="yyyy-MM-dd" type="text" width="10"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
        <span class="add-on">
          <em>napr. 2013-01-01</em>
        </span>
      </div>
      
      <%= f.label :time, "Čas" %>
      <%= f.text_field :time %>
      
      <%= f.label :note, "Poznámka" %>
      <%= f.text_area :note, placeholder: "Poznámka k zjazdu...", size: "x3" %>
      
      <%= f.submit "Pridaj", class: "btn btn-large btn-primary" %>
      
      
      <script type="text/javascript">      
      $(function() {
        $('#datetimepicker').datetimepicker({
          pickTime: false,
        });
        var picker = $('#datetimepicker').data('datetimepicker');
        picker.setLocalDate(new Date()); 
      });
      </script>
 
<script>
  $(document).ready(function() {
    $('#locations_select').change(function() {
      $.ajax({
        url: "<%= update_areas_path %>",
        data: {
        location_id : $('#locations_select').val()
      },
      dataType: "script"
    });
  });
  
  $('#areas_select').change(function() {
    $.ajax({
      url: "<%= update_tracks_path %>",
      data: {
      area_id : $('#areas_select').val()
      },
      dataType: "script"
    });
  });
  });
</script>
    <% end %>
  </div>
</div>

app/views/achievements/update_areas.js.erb
$('#areas_select').html("<%= escape_javascript(options_for_select(@areas)) %>");

app/views/achievements/update_tracks.js.erb
$('#tracks_select').html("<%= escape_javascript(options_for_select(@tracks)) %>");