config/routes.rb
Skialpi::Application.routes.draw do
 
  root :to => 'static_pages#home'
  
  resources :bug_reports
  resources :users do
    member do
      get :achievements
      get :season
      get :top10
      get :stats
      get :turn_off_helpers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :locations
  resources :areas
  resources :tracks
  resources :achievements
  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/skusam', to: 'users#skusam'
  match '/skusam_sprac', to: 'users#skusam_sprac', via: 'put'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/registration', to: 'users#new'
  
  match '/locations/:id/area/new' => 'areas#new'
  match '/locations/:id/area/create' => 'areas#create', via: 'post'
  
  match '/areas/:id/track/new' => 'tracks#new'
  match '/areas/:id/track/create' => 'tracks#create', via: 'post'
  
  match '/tracks/:id/change_area' => 'tracks#change_area'
  match '/tracks/:id/change_area_proc' => 'tracks#change_area_proc', via: 'put'
  match '/tracks/:id/add_as_achievement' => 'tracks#add_as_achievement'
  match '/tracks/:id/add_as_achievement_proc' => 'tracks#add_as_achievement_proc', via: 'post'
  
   match 'update_areas' => 'achievements#update_areas'
   match 'update_tracks' => 'achievements#update_tracks'

   match 'stats' => 'stats#index'
   match 'stats/best' => 'stats#best'
   match 'stats/best_in_season' => 'stats#best_in_season'

   
 

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
  attr_accessible :name, :description, :access, :conditions
  
  validates :name, presence: true, length: { maximum: 150 }
  
  has_many :areas, dependent: :destroy
  
  default_scope order: :name
  
end

app/controllers/locations_controller.rb
# encoding: utf-8

class LocationsController < ApplicationController

  before_filter :signed_in_user, except: [:index, :show]
  
  before_filter :admin_user, only: :destroy
  
  def new
    @location = Location.new
  end
  
  def create
    @location = Location.new(params[:location])
    if @location.save
      flash[:success] = "Lokalita bola úspešne pridaná."
      redirect_to locations_path
    else
      render 'new'
    end
  end
  
  def edit
    @location = Location.find(params[:id])
  end
  
  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      flash[:success] = "Údaje o lokalite boli zmenené."
      redirect_to @location
    else
      render 'edit'
    end
  end
  
  def index
    @locations = Location.paginate(page: params[:page]).order(:name)
  end
  
  def show
    @location = Location.find(params[:id])
    @areas = @location.areas.paginate(page: params[:page])
  end
  
  def destroy
    Location.find(params[:id]).destroy
    flash[:success] = "Lokalita bola zmazaná."
    redirect_to "/locations"
  end
  
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<% provide(:title, 'Editácia lokality') %>

<h1>Editácia lokality</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@location) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Názov *" %>
      <%= f.text_field :name %>
      

      <%= f.label :description, "Popis" %>
      <%= f.text_area :description, placeholder: "Tu zadajte popis lokality ...", size: "x3" %>
      
      <%= f.label :conditions, "Podmienky" %>
      <%= f.text_area :conditions, placeholder: "Tu zhrňte podmienky v danej lokalite ...", size: "x3" %>
      
      <%= f.label :access, "Prístup" %>
      <%= f.text_area :access, placeholder: "Popíšte prístup do danej lokality ...", size: "x3" %>
      
        
      Údaje označené hviezdičkou (*) sú povinné  <br /> <br />
        
      <%= f.submit "Zmeň", class: "btn btn-large btn-primary" %>
      
      
    <% end %>
    

  </div>
</div>

app/views/locations/index.html.erb
<% provide(:title, "Lokality") %>

<h1> Lokality </h1>

<% if signed_in? %>
  <div class="alert alert-info">
  Ak chcete <em> pridať nový zjazd </em>, vyberte si lokalitu, potom oblasť a pridajte nový zjazd. Ak sa lokalita nenachádza v zozname, <u><%= link_to "vytvorte ju tu", "/locations/new" %></u>
  </div>
<% end %>

<% if signed_in? and current_user.helpers %>
    <div class="alert alert-info center">
      Ak sa chcete dozvedieť viac o nejakom zjazde, vyberte si lokalitu, v ktorom sa nachádza. Každá lokalita zoskupuje niekoľko skialpinistických oblastí. V týchto oblastiach sa potom nachádzajú už konkrétne zjazdy.
    </div>
<% end %>

<%= will_paginate %>


<% if @locations.length == 0 %>
   <div class="alert alert-warning center" style="margin-top: 50px">V systéme nie sú evidované žiadne lokality.</div>
   <br/><br/>
<% else %>

<table class="table table-striped">
  
  <% @locations.each do |location| %>
    <tr>
      <td> <%= link_to location.name, location %> </td>
      <% if signed_in? %>
      <td> <%= link_to '[upraviť]', edit_location_path(location) %> </td>
      <td> <%= link_to '[pridať oblasť]', "/locations/#{location.id}/area/new" %> </td>
      <% if current_user.admin? %>
      <td> <%= link_to "[odstrániť]", location, method: :delete,
                                    data: { confirm: "Ste si istí?" } %>
      </td>
      <% end %>
      <% end %>
    </tr>
  <% end %>

</table>

<%= will_paginate %>
<% end %>

<% if signed_in? %>
  <p class="center"><%= link_to "Vytvoriť novú lokalitu", "/locations/new", class: "btn btn-primary" %></p>
<% end %>

app/views/locations/new.html.erb
<% provide(:title, 'Evidovanie lokality') %>

<h1>Evidovanie lokality</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@location) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Názov *" %>
      <%= f.text_field :name %>
      

      <%= f.label :description, "Popis" %>
      <%= f.text_area :description, placeholder: "Tu zadajte popis lokality ...", size: "x3" %>
      
      <%= f.label :conditions, "Podmienky" %>
      <%= f.text_area :conditions, placeholder: "Tu zhrňte podmienky v danej lokalite ...", size: "x3" %>
      
      <%= f.label :access, "Prístup" %>
      <%= f.text_area :access, placeholder: "Popíšte prístup do danej lokality ...", size: "x3" %>
      
        
      Údaje označené hviezdičkou (*) sú povinné  <br /> <br />
        
      <%= f.submit "Pridaj", class: "btn btn-large btn-primary" %>
      
    <% end %>
    

  </div>
</div>

app/views/locations/show.html.erb
<% provide(:title, @location.name) %>

<h1><%= @location.name %></h1>

<div class="row">
  <div class="span6 offset3">

    <% unless @location.description.empty? %>
    <p>
      <h4>Popis</h4>
      <%= @location.description %>
      <% if signed_in? %>
        <%= link_to '[upraviť]', edit_location_path(@location) %>
      <% end %>
    </p>
    <% end %>
    
    <% unless @location.access.empty? %>
    <p>
      <h4>Prístup</h4>
      <%= @location.access %>
      <% if signed_in? %>
        <%= link_to '[upraviť]', edit_location_path(@location) %>
      <% end %>
    </p>
    <% end %>
    
    <% unless @location.conditions.empty? %>
    <p>
      <h4>Podmienky</h4>
      <%= @location.conditions %>
      <% if signed_in? %>
        <%= link_to '[upraviť]', edit_location_path(@location) %>
      <% end %>
    </p>
    <% end %>
    
    
    <h4>Oblasti</h4> 
    
    <% if signed_in? %>
      Ak chcete <em> pridať zjazd </em>, vyberte si oblasť, do ktorej patrí, alebo túto oblasť <%= link_to "vytvorte", "/locations/#{@location.id}/area/new" %> v zobrazovanej lokalite.
      <br /><br />
    <% end %> 
    

    <% if @areas.length == 0 %>
      <div class="alert alert-warning center" style="margin-top: 50px">
        Pre túto lokalitu nie sú evidované žiadne oblasti.
      </div>
      <br /><br />
    <% else %>  

    <table class="table table-striped">
 
    <% @areas.each do |area| %>
    <tr>
      <td> <%= link_to area.name, area %> </td>
      <% if signed_in? %>
      <td> <%= link_to "[upraviť]", edit_area_path(area) %>
      <% if current_user.admin? %>
      <td>
        <%= link_to "[zmazať]", area, method: :delete,
                                  data: { confirm: "Ste si istí?" } %>
      </td>
      <% end %>
      <% end %>
    </tr>
    <% end %>

    </table>
    <%= will_paginate(@areas) %>

    <% end %>
    
    <% if signed_in? %>
      <p class="center">
        <%= link_to "Pridať novú oblasť", "/locations/#{@location.id}/area/new", class: "btn btn-primary"%>
      </p>
      <br />
    <% end %>
    <%= link_to "<< Späť na zoznam lokalít", "/locations" %>

  </div>
</div>