config/routes.rb
Skialpi::Application.routes.draw do
 
  root :to => 'static_pages#home'
  
  resources :bug_reports
  resources :users do
    member do
      get :achievements
      get :season
      get :top10
      get :stats
      get :turn_off_helpers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :locations
  resources :areas
  resources :tracks
  resources :achievements
  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/skusam', to: 'users#skusam'
  match '/skusam_sprac', to: 'users#skusam_sprac', via: 'put'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/registration', to: 'users#new'
  
  match '/locations/:id/area/new' => 'areas#new'
  match '/locations/:id/area/create' => 'areas#create', via: 'post'
  
  match '/areas/:id/track/new' => 'tracks#new'
  match '/areas/:id/track/create' => 'tracks#create', via: 'post'
  
  match '/tracks/:id/change_area' => 'tracks#change_area'
  match '/tracks/:id/change_area_proc' => 'tracks#change_area_proc', via: 'put'
  match '/tracks/:id/add_as_achievement' => 'tracks#add_as_achievement'
  match '/tracks/:id/add_as_achievement_proc' => 'tracks#add_as_achievement_proc', via: 'post'
  
   match 'update_areas' => 'achievements#update_areas'
   match 'update_tracks' => 'achievements#update_tracks'

   match 'stats' => 'stats#index'
   match 'stats/best' => 'stats#best'
   match 'stats/best_in_season' => 'stats#best_in_season'

   
 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Skialpi (c) Juraj Šimek 2013
  </small>
  <nav>
    <ul>
      <li><%= link_to "O mne",   about_path %></li>
      <li><%= link_to "Pomocník", help_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <% if signed_in? %>
         <li><%= link_to "Ohlásiť chybu", "/bug_reports/new" %></li>
         <% if current_user.admin? %>
            <li><%= link_to "Zoznam chýb", "/bug_reports" %></li>
         <% end %>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "skialpi", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Domov", root_path %></li>
          <li><%= link_to "Štatistiky", stats_path %></li>
          <li><%= link_to "Denníčky", users_path %></li>

          <li><%= link_to "Lokality (zjazdy)", "/locations" %></li>
          
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Účet <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Môj denníček", current_user %></li>
                <li><%= link_to "Nastavenia účtu", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Odhlásenie", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Prihlásenie", signin_path %></li>
          <% end %>  
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  
</html>